### ISSUE TITLE
Does not work on Jupterlab

### ISSUE THREAD

**Issue by BBassi** [nmearl/ipygoldenlayout#11]
jovyan@jupyter-jupyterlab-2djupyterlab-2ddemo-2d5torb9md:~$ jupyter labextension install ipygoldenlayout
Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-jhpszc8a.log
jovyan@jupyter-jupyterlab-2djupyterlab-2ddemo-2d5torb9md:~$ cat /tmp/jupyterlab-debug-jhpszc8a.log
Node v11.14.0

Yarn configuration loaded.
> /srv/conda/envs/notebook/bin/npm pack ipygoldenlayout
npm notice 
npm notice 📦  ipygoldenlayout@0.1.0
npm notice === Tarball Contents === 
npm notice 2.8kB   package.json    
npm notice 1.5kB   LICENSE.txt     
npm notice 752B    README.md       
npm notice 700.9kB dist/index.js   
npm notice 754B    lib/extension.js
npm notice 361B    lib/index.js    
npm notice 1.1kB   lib/plugin.js   
npm notice 533B    lib/version.js  
npm notice 5.1kB   lib/widget.js   
npm notice === Tarball Details === 
npm notice name:          ipygoldenlayout                         
npm notice version:       0.1.0                                   
npm notice filename:      ipygoldenlayout-0.1.0.tgz               
npm notice package size:  205.6 kB                                
npm notice unpacked size: 713.8 kB                                
npm notice shasum:        2b0b5b6c782524848fdd46d25a056a611b7d6f5e
npm notice integrity:     sha512-OwsrKUV8mTpm9[...]KwKZff+tdos5g==
npm notice total files:   9                                       
npm notice 
ipygoldenlayout-0.1.0.tgz

Node v11.14.0

Yarn configuration loaded.
Building jupyterlab assets (build:prod:minimize)
> node /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @lumino/coreutils@1.5.2" has unmet peer dependency "crypto@1.0.1".
warning "jupyter-leaflet > leaflet.markercluster@1.4.1" has incorrect peer dependency "leaflet@~1.3.1".
[5/5] Building fresh packages...
success Saved lockfile.
Done in 11.61s.

> node /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 1.27s.

> node /srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ ensure-max-old-space webpack --config webpack.prod.minimize.config.js
ModuleNotFoundError: Module not found: Error: Can't resolve './custom.css' in '/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/ipygoldenlayout/lib'
    at factory.create (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:925:10)
    at factory (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
    at resolver (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/neo-async/async.js:2830:7
    at /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
    at hook.callAsync (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
    at hook.callAsync (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
    at hook.callAsync (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn43 (eval at create (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at hook.callAsync (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
    at hook.callAsync (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn1 (eval at create (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at hook.callAsync (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
    at _fn0 (eval at create (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at fs.stat (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15)
    at process.nextTick (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15)
    at processTicksAndRejections (internal/process/task_queues.js:79:9)
resolve './custom.css' in '/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/ipygoldenlayout/lib'
  using description file: /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/ipygoldenlayout/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/ipygoldenlayout/package.json (relative path: ./lib/custom.css)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/ipygoldenlayout/lib/custom.css doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/ipygoldenlayout/lib/custom.css.wasm doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/ipygoldenlayout/lib/custom.css.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/ipygoldenlayout/lib/custom.css.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/ipygoldenlayout/lib/custom.css.json doesn't exist
      as directory
        /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/ipygoldenlayout/lib/custom.css doesn't exist
child_process.js:660
    throw err;
    ^

Error: Command failed: /srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/.bin/webpack --config webpack.prod.minimize.config.js
    at checkExecSyncError (child_process.js:639:11)
    at Object.execFileSync (child_process.js:657:15)
    at Object.<anonymous> (/srv/conda/envs/notebook/share/jupyter/lab/staging/node_modules/@jupyterlab/buildutils/lib/ensure-max-old-space.js:38:17)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    command=command, app_options=app_options)

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/commands.py", line 460, in build
    command=command, clean_staging=clean_staging)

  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/jupyterlab/commands.py", line 661, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter

**Comment by BBassi** [comment]
Works now - thanks
