### ISSUE TITLE
Installation challenges; add node.js to required packages?

### ISSUE THREAD

**Issue by bmorris3** [nmearl/ipygoldenlayout#35]
Hi all, 

I installed ipygoldenlayout today and didn't already have node.js installed. Maybe we should add to the README that you may need to 
```
conda install -c conda-forge nodejs
```
before you install the labextension?

Also, I'm getting the following error when I run the labextension install command: 
```
Node v18.9.0

Yarn configuration loaded.
> /opt/miniconda3/bin/npm pack ipygoldenlayout
npm notice
npm notice 📦  ipygoldenlayout@0.1.0
npm notice === Tarball Contents ===
npm notice 1.5kB   LICENSE.txt
npm notice 752B    README.md
npm notice 700.9kB dist/index.js
npm notice 754B    lib/extension.js
npm notice 361B    lib/index.js
npm notice 1.1kB   lib/plugin.js
npm notice 533B    lib/version.js
npm notice 5.1kB   lib/widget.js
npm notice 2.8kB   package.json
npm notice === Tarball Details ===
npm notice name:          ipygoldenlayout
npm notice version:       0.1.0
npm notice filename:      ipygoldenlayout-0.1.0.tgz
npm notice package size:  205.6 kB
npm notice unpacked size: 713.8 kB
npm notice shasum:        2b0b5b6c782524848fdd46d25a056a611b7d6f5e
npm notice integrity:     sha512-OwsrKUV8mTpm9[...]KwKZff+tdos5g==
npm notice total files:   9
npm notice
ipygoldenlayout-0.1.0.tgz

Node v18.9.0

Yarn configuration loaded.
Building jupyterlab assets (production, minimized)
> node /opt/miniconda3/lib/python3.9/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.16s.

> node /opt/miniconda3/lib/python3.9/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /opt/miniconda3/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.22s.

> node /opt/miniconda3/lib/python3.9/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve './custom.css' in '/opt/miniconda3/share/jupyter/lab/staging/node_modules/ipygoldenlayout/lib'
    at /opt/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:1768:28
    at /opt/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:742:13
    at eval (eval at create (/opt/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /opt/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:276:22
    at eval (eval at create (/opt/miniconda3/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /opt/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:405:22
    at /opt/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:119:11
    at /opt/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:650:24
    at /opt/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:813:8
    at /opt/miniconda3/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:933:5
resolve './custom.css' in '/opt/miniconda3/share/jupyter/lab/staging/node_modules/ipygoldenlayout/lib'
  using description file: /opt/miniconda3/share/jupyter/lab/staging/node_modules/ipygoldenlayout/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /opt/miniconda3/share/jupyter/lab/staging/node_modules/ipygoldenlayout/package.json (relative path: ./lib/custom.css)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /opt/miniconda3/share/jupyter/lab/staging/node_modules/ipygoldenlayout/lib/custom.css doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /opt/miniconda3/share/jupyter/lab/staging/node_modules/ipygoldenlayout/lib/custom.css.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /opt/miniconda3/share/jupyter/lab/staging/node_modules/ipygoldenlayout/lib/custom.css.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /opt/miniconda3/share/jupyter/lab/staging/node_modules/ipygoldenlayout/lib/custom.css.wasm doesn't exist
      as directory
        /opt/miniconda3/share/jupyter/lab/staging/node_modules/ipygoldenlayout/lib/custom.css doesn't exist
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
```

**Comment by jhgoebbert** [comment]
Are you trying to install `ipygoldenlayout` to `JupyterLab>=4`?  
Probably `ipygoldenlayout` does not support a version >=4 of JupyterLab, yet.
